# # # DICTIONARY COLLECTION OF KEY VALUE PAIRS UNORDEREDNBUT ACCESED BY KEYS
# # example
# # TYPE OF CONVERSION IS THE PROCESS OF CHAINGING AVALUE FROM ONE DATA TYPE
# # LIST-TUPLE

# list[1,2,3,4]
# tuple=tuple[list]
# print(tuple)
# print(type(tuple))

# tuple=(5,6,7)
# list=list(tuple)
# print(list)
# print(type(list))

# # LIST-SETS(REMOVE DUPLICATES)
# # USE A SET ONLY WHEN UNIQUE VALUES ARE NEEDED
# my_list=(1,2,2,3,3,4)
# my_set=set(my_list)
# print(my_set)
# print(type(my_set))

# # SET-LIST
# # order after converting to list 
# my_set={10,20,30}
# my_list=list(my_set)
# print(my_list)
# print(type(my_list))

# # # DICTONARY
# student={'name':'john','age':20,'grade':'A'}
# keys_list=list(student.keys())
# print(keys_list)

# student={'name':'john','age':20,'grade':'A'}
# values_list=list(student.values())
# print(values_list)

# student={'name':'john','age':20,'grade':'A'}
# items_list=(student.items())
# print(items_list)


import array 
numbers=array.array('i'(1,2,3,4,5))
print(numbers)

import array
floats=array.array('f'[1,2,3,4,5,6])
print(float)


import array
nums=array.array('i'(10,20,30,40))
print(nums(0))
print(nums(2))

# # slicing array
# import array
# nums=array.array('i'(10,20,30,40,50))


# Basic operations on arrya
print(len(numbers))
print(sum(numbers))
print(max(numbers))
print(min(numbers))





